name: ci
on: [push, pull_request]

jobs:
  linux-openmpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Open MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin libopenmpi-dev

      - name: Configure (Release)
        run: cmake -S sources -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Test
        env:
          OMPI_MCA_rmaps_base_oversubscribe: "1"
        run: ctest --test-dir build --output-on-failure -V